/*
설유진 2025/07/18
sql 연습문제
*/

-- 실습 1-1
alter session set "_oracle_script"= true;
CREATE USER shop IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO shop;\

-- 실습 1-2
create table customer(
    cid varchar2(20) primary key,
    name varchar2(20) not null,
    hp char(13) unique,
    address varchar2(200) ,
    rdate date not null
 
    );
create table product(
    pno varchar2(20) primary key,
    pname varchar2(30) not null,
    stock number default 0,
    price number,
    company varchar(20)

    );
CREATE TABLE orders (
    ord_no    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ord_cid   VARCHAR2(20) NOT NULL,
    ord_pno   NUMBER(4) NOT NULL,
    ord_cnt   NUMBER DEFAULT 1,
    ord_date  TIMESTAMP NOT NULL
);

drop table orders;


-- 실습 1-3
INSERT INTO customer VALUES ('c101', '김유신', '010-1234-1001', '김해','2022-01-01');
INSERT INTO customer VALUES ('c102', '김춘추', '010-1234-1002', '경주','2022-01-02');
INSERT INTO customer VALUES ('c103', '장보고', '010-1234-1003', '완도','2022-01-03');
INSERT INTO customer VALUES ('c104', '강감찬', '010-1234-1004', '마포구','2022-01-04');
INSERT INTO customer VALUES ('c105', '이성계', NULL, NULL,'2022-01-05');
INSERT INTO customer VALUES ('c106', '정철', '010-1234-1006', '용인','2022-01-06');
INSERT INTO customer VALUES ('c107', '허준', NULL, NULL,'2022-01-07');
INSERT INTO customer VALUES ('c108', '이순신', '010-1234-1008', '영등포','2022-01-08');
INSERT INTO customer VALUES ('c109', '송상현', '010-1234-1009', '부산 동래','2022-01-09');
INSERT INTO customer VALUES ('c1010', '정약용', '010-1234-1010', '광주','2022-01-10');


INSERT INTO product VALUES (1, '새우깡', 5000, 1500, '농심');
INSERT INTO product VALUES (2, '초코파이', 2500, 2500, '오리온');
INSERT INTO product VALUES (3, '포카칩', 3600, 1700, '오리온');
INSERT INTO product VALUES (4, '양파링', 1250, 1800, '농심');
INSERT INTO product VALUES (5, '죠리퐁', 2200, NULL, '크라운');
INSERT INTO product VALUES (6, '마가렛트', 3500, 3500, '롯데');
INSERT INTO product VALUES (7, '뿌셔뿌셔', 1650, 1200, '오뚜기');

INSERT INTO orders (ord_cid,ord_pno,ord_cnt,ord_date) VALUES ('c102', 3, 2, '2022-07-01 13:15:10');
INSERT INTO orders (ord_cid,ord_pno,ord_cnt,ord_date) VALUES ( 'c101', 4, 1, '2022-07-01 14:16:11');
INSERT INTO orders (ord_cid,ord_pno,ord_cnt,ord_date) VALUES ( 'c108', 1, 1, '2022-07-01 17:23:18');
INSERT INTO orders (ord_cid,ord_pno,ord_cnt,ord_date) VALUES ( 'c109', 6, 5, '2022-07-02 10:46:36');
INSERT INTO orders (ord_cid,ord_pno,ord_cnt,ord_date) VALUES ( 'c102', 2, 1, '2022-07-03 09:15:37');
INSERT INTO orders (ord_cid,ord_pno,ord_cnt,ord_date) VALUES ( 'c101', 7, 3, '2022-07-03 12:35:12');
INSERT INTO orders (ord_cid,ord_pno,ord_cnt,ord_date) VALUES ( 'c110', 1, 2, '2022-07-03 16:55:36');
INSERT INTO orders (ord_cid,ord_pno,ord_cnt,ord_date) VALUES ( 'c104', 2, 4, '2022-07-04 14:23:23');
INSERT INTO orders (ord_cid,ord_pno,ord_cnt,ord_date) VALUES ( 'c102', 1, 3, '2022-07-04 21:54:34');
INSERT INTO orders (ord_cid,ord_pno,ord_cnt,ord_date) VALUES ( 'c107', 6, 1, '2022-07-05 14:21:03');




-- 실습 1-4
select * from customer;
-- 실습 1-5
select cid,name,hp from customer;
-- 실습 1-6
select * from product;
-- 실습 1-7
select company from product;

-- 실습 1-8
select distinct company from product;

-- 실습 1-9
SELECT pname,price FROM product;

-- 실습 1-10
select pname,price+500 as "조정단가" from product;

-- 실습 1-11
select * from product;
select pname,stock,price from product where company = '오리온';
-- 실습 1-12
select * from orders;
select ord_pno,ord_cnt,ord_date from orders where ord_cid = 'c102';
-- 실습 1-13
select ord_pno,ord_cnt,ord_date from orders where ord_cid='c102' and ord_cnt >=2;
-- 실습 1-14
select * from product where price between 1000 and 2000;
-- 실습 1-15
select cid,name,hp,address from customer where name like '김%';
-- 실습 1-16
select cid, name,hp ,address from customer where name like '__';
-- 실습 1-17
select * from customer where hp is null;
-- 실습 1-18
select * from customer where address is not null;
-- 실습 1-19
select * from customer order by rdate desc;
-- 실습 1-20
select *from orders where ord_cnt >=3 order by ord_cnt desc, ord_pno asc;
-- 실습 1-21
select avg(price) from product;
-- 실습 1-22
select * from product;
select sum(stock) as "재고량 합계 " from product where company = '농심';

-- 실습 1-23
select count(*) as "고객수" from customer;
-- 실습 1-24
select  * from product;
select count(distinct company) as "제조업체 수" from product;

-- 실습 1-25
select * from orders;
select ord_pno as "주문상품번호", sum(ord_cnt) as "총주문수량" 
    from orders
    group by ord_pno order by ord_pno;
-- 실습 1-26
select company as 제조업체 ,count(*) as 제품수 , max(price) as 최고가 
    from product
    group by company order by company;
-- 실습 1-27
SELECT company AS 제조업체, COUNT(*) AS 제품수, MAX(price) AS 최고가  
    FROM product  
    GROUP BY company  
    HAVING COUNT(company) >= 2;

-- 실습 1-28
select ord_pno,ord_cid,sum(ord_cnt) as "총주문 수량" from orders
    group by ord_cid,ord_pno order by ord_pno;

-- 실습 1-29
select ord_cid,pname from orders a
    JOIN Product c 
    on a.ORD_PNO = c.pno 
    where ord_cid = 'c102' order by pname desc;
    
-- 실습 1-30
select ord_cid ,name,pname,ord_date from orders a
    JOIN Customer b on a.ORD_CID = b.cid
    JOIN Product c on a.ORD_PNO = c.pno
    WHERE TO_CHAR(ord_date, 'MM-DD') = '07-03';
    
    select ord_cid ,name,pname,ord_date from orders a
    JOIN Customer b on a.ORD_CID = b.cid
    JOIN Product c on a.ORD_PNO = c.pno
    WHERE ord_date like '2022-07-03%';